import type { Metadata } from "next";
import "../styles/globals.css";
import { ThemeProvider } from "@/provider/theme-provider";
import { inter } from "@/lib/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru" suppressHydrationWarning>
      <body className={`${inter.className} antialiased min-h-screen`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <main className="p-5 max-w-screen-2xl mx-auto">{children}</main>
        </ThemeProvider>
      </body>
    </html>
  );
}
